"""Centralized regex patterns and constants for statement parsing and categorization.

This module consolidates patterns from pdf_parser.py and categorize.py
to improve maintainability and reduce duplication.
"""

import re
from typing import Dict, List

# ============================================================================
# PDF Parser Constants
# ============================================================================

STATEMENT_PERIOD_RX = re.compile(
    r"""
    (?:
        Statement \s+ Period .*?
    )?
    (\d{1,2}[/-]\d{1,2}[/-](\d{2,4}))
    \s*-\s*
    (\d{1,2}[/-]\d{1,2}[/-](\d{2,4}))
    """,
    re.IGNORECASE | re.VERBOSE,
)

DATE_START_RX = re.compile(
    r"""
    ^(?P<date>
        \d{1,2} [/-] \d{1,2}
        (?: [/-] \d{2,4} )?
    )
    (?!\s*-\s*\d{1,2}[/-]\d{1,2})
    \b
    """,
    re.VERBOSE,
)

AMOUNT_TOKEN_RX = re.compile(
    r"""
    ^
    (?:
        \( (?P<num_paren> \$? (?: (?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d{2})? | \.\d{2} ) ) \)
        |
        (?P<sign>-)? \$? (?: (?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d{2})? | \.\d{2} ) (?P<trail_minus>-)?
    )$
    """,
    re.VERBOSE,
)

YEAR_IN_RANGE_RX = re.compile(
    r"""
    \b
    \d{1,2} [/-] \d{1,2} [/-] (\d{2,4})
    \b
    """,
    re.VERBOSE,
)

ACCOUNT_NAME_NUMBER_CORE = r"""
(?P<name>
    [A-Za-z&'./-]+
    (?:\s+[A-Za-z&'./-]+)*
)
\s* - \s*
(?P<number>\d{6,})\b
"""

ACCOUNT_HEADER_RX = re.compile(rf"^\s*{ACCOUNT_NAME_NUMBER_CORE}", re.VERBOSE)
ACCOUNT_HEADER_INLINE_RX = re.compile(ACCOUNT_NAME_NUMBER_CORE, re.VERBOSE)

DATE_RANGE_RX = re.compile(
    r"""
    ^\d{1,2}[/-]\d{1,2}[/-]\d{2,4}
    \s*-\s*
    \d{1,2}[/-]\d{1,2}[/-]\d{2,4}$
    """,
    re.VERBOSE,
)

HEADER_FOOTER_PATTERNS_RX = [
    re.compile(r"^Page \s+\d+ \s+ of \s+ \d+$", re.IGNORECASE | re.VERBOSE),
    re.compile(r"^Statement \s+ Period$", re.IGNORECASE | re.VERBOSE),
    re.compile(r"^Statement \s+ of \s+ Account$", re.IGNORECASE | re.VERBOSE),
]

DATE_PREFIX_RX = re.compile(r"^\d{1,2}[/-]\d{1,2}(?:[/-]\d{2,4})?\b")

BALANCE_SKIP_RX = re.compile(
    r"\b((BEGINNING|OPENING) BALANCE|(ENDING|CLOSING) BALANCE|BALANCE FORWARD|NEW BALANCE)\b",
    re.IGNORECASE,
)

CREDIT_CARD_DETECT_PATTERNS = [
    re.compile(r"Minimum Payment Due", re.IGNORECASE),
    re.compile(r"Credit Limit", re.IGNORECASE),
    re.compile(r"Statement Closing Date", re.IGNORECASE),
]

CC_TXN_LINE_RX = re.compile(
    r"^(?P<trans_date>\d{1,2}[/-]\d{1,2}(?:[/-]\d{2,4})?)\s+"  # transaction date
    r"(?P<post_date>\d{1,2}[/-]\d{1,2}(?:[/-]\d{2,4})?)\s+"  # post date
    r"(?P<ref>\d{8,})\s+"  # long reference number
    r"(?P<rest>.+?)\s+\$?(?P<amount>[0-9,]+(?:\.\d{2})?)$"  # description + amount
)

CC_SECTION_HEADER_RX = re.compile(
    r"^(TRANSACTIONS|PAYMENTS AND CREDITS|TOTAL .*|Rewards Details|REWARD POINT SUMMARY)$",
    re.IGNORECASE,
)

DATE_FORMATS = (
    "%m-%d-%Y",
    "%m-%d-%y",
    "%d-%m-%Y",
    "%d-%m-%y",
    "%m/%d/%Y",
    "%m/%d/%y",
    "%d/%m/%Y",
    "%d/%m/%y",
)

SKIP_DESC = ["Beginning Balance", "Ending Balance"]
SKIP_CONTAINS = ["Average Daily Balance", "Beginning Balnce", "Ending Balance"]

CC_PAYMENT_KEYWORDS = [
    "PAYMENT RECEIVED",
    "PAYMENT",
    "PMT",
    "AUTOPAY",
    "ONLINE PAYMENT",
    "ELECTRONIC PAYMENT",
    "ACH PAYMENT",
    "BILL PAYMENT",
]
CC_CREDIT_KEYWORDS = ["CREDIT", "REFUND", "REVERSAL"]

# ============================================================================
# Categorization Constants
# ============================================================================

CANONICAL_CATEGORIES: List[str] = [
    "Housing",
    "Transportation",
    "Food",
    "Utilities",
    "Health",
    "Recreation",
    "Finance",
]

DEFAULT_CATEGORY_REGEX: Dict[str, List[str]] = {
    "Housing": [
        r"\b(MORTGAGE|RENT|HOME ?LOAN|LOAN PAYMENT)\b",
        r"\b(LOWE'S|HOME DEPOT|MENARDS)\b",
        r"\b(HOA|PROPERTY TAX|PROPERTY TAXES|APARTMENT|APT\b|LEASE PAYMENT)\b",
        r"\b(IKEA|WAYFAIR|OVERSTOCK|ASHLEY FURNITURE|FURNITURE)\b",
        r"\b(HVAC|PLUMB(ER|ING)|ELECTRICIAN|ROOF(ING)?|PEST CONTROL)\b",
        r"\b(LAWN CARE|LANDSCAPING|GARDEN CENTER|HOME IMPROVEMENT)\b",
        r"\b(SECURITY SYSTEM|ADT SECURITY|RING SUBSCRIPTION)\b",
        r"\b(REMODEL|REMODELING|CONTRACTOR|BUILDERS|GENERAL CONTRACTOR|PAINT SUPPLY)\b",
        r"\b(PROPERTY MANAGEMENT|PROPERTY MGMT|PROPERTY MGT)\b",
        r"\b(LEASE/RNT|RENTAL AGENCY|RENTAL PAYMENT|LANDLORD)\b",
        r"\b(SECURITY DEPOSIT|MOVE[- ]IN FEE|MOVE-IN FEE)\b",
        r"\b(HOME INSURANCE|HOMEOWNER'S INSURANCE|HOMEOWNERS INSURANCE|HOA FEE)\b",
        r"\b(MORTGAGE INTEREST|ESCROW|ESCROW PAYMENT|MORTGAGE SERVICER)\b",
        r"\b(HOUSE CLEANING|CLEANING SERVICE|MAID SERVICE)\b",
        r"\b(APPLIANCE REPAIR|APPLIANCE SERVICE|REFRIGERATOR REPAIR|WASHER REPAIR)\b",
        r"\b(CONDO FEE|CONDO ASSESSMENT|CO-OP FEE)\b",
        r"\b(CABINETRY|COUNTERTOP|TILE SHOP|POOL SERVICE)\b",
        r"\b(HOA PAYMENT|HOA DUES|HOA FEE)\b",
        r"\b(FOUNDATION REPAIR|BASEMENT REPAIR|CONCRETE REPAIR)\b",
        r"\b(PLUMBING SUPPLY|ELECTRICAL SUPPLY|HVAC SUPPLY)\b",
    ],
    "Transportation": [
        r"\b(LYFT|UBER|METRO|SUBWAY|TRAIN|PARKING|TOLL)\b",
        r"\b(SHELL|EXXON|CHEVRON|BP|GAS STATION|FUEL)\b",
        r"\b(AUTO LOAN|CAR PAYMENT|CAR WASH)\b",
        r"\b(AUTOZONE|O'REILLY|OREILLY|ADVANCE AUTO|NAPA AUTO|AUTO PARTS)\b",
        r"\b(OIL CHANGE|MECHANIC|TIRES?|TIRE KING|DISCOUNT TIRE|JIFFY LUBE|QUICK LUBE)\b",
        r"\b(U-?HAUL|RENTAL CAR|ENTERPRISE RENTAL|ENTERPRISE RENT|HERTZ|AVIS|BUDGET RENTAL)\b",
        r"\b(DMV|VEHICLE REG(ISTRATION)?|EMISSIONS TEST|SMOG CHECK)\b",
        r"\b(EV CHARGE|CHARGING STATION|SUPERCHARGER)\b",
        r"\b(CHASE AUTOMOTIVE|AUTO FINANCE|AUTO PMT|AUTO PAYMENT|AUTO LOANS?)\b",
        r"\b(BIKE SHOP|CYCLE SHOP|LYFT BIKE|BIRD RIDE|LIME|SCOOTER|VELO|RENT A BIKE)\b",
        r"\b(EXXONMOBIL|MOBIL|SUNCOR|CONOCO|GAS N GO|GAS-N-GO)\b",
        r"\b(TESLA SERVICE|TESLA|CARMAX|AUTONATION|CARVANA)\b",
        r"\b(PARKMOBILE|PARKING LOT|PARKNOW|PARKING METER)\b",
        r"\b(EZPASS|TOLLTAG|TOLL CHARGE|TOLL COLLECTION)\b",
        r"\b(AMTRAK|GREYHOUND|FLIXBUS|BOLT BUS)\b",
        r"\b(TRANSIT AUTHORITY|MTA|BART|SEPTA|CTA|WMATA)\b",
        r"\b(TRANSPORTATION FEE|AIRPORT SHUTTLE|SHUTTLE SERVICE)\b",
        r"\b(MOTORCYCLE SHOP|MOTORCYCLE REPAIR|MOTORCYCLE PARTS)\b",
        r"\b(TAXI|CAB SERVICE|BLACK CAB)\b",
        r"\b(BUS PASS|MONTHLY PASS|TRANSIT PASS)\b",
    ],
    "Food": [
        r"\b(WALMART|SAFEWAY|KROGER|WHOLE ?FOODS|TRADER JOE'S|ALDI|LIDL|PUBLIX)\b",
        r"\b(STARBUCKS|UBER EATS|DOORDASH|GRUBHUB|CAFE|DINER|PIZZA|CHIPOTLE|MCDONALD|MCDONALD'S|BURGER KING|SUBWAY|TACO BELL|RESTAURANT)\b",
        r"\b(COSTCO|SAM'S CLUB|SAMS CLUB|BJ'S WHOLESALE|WHOLESALE CLUB)\b",
        r"\b(GROCERY OUTLET|FRESH THYME|HEALTHY FOOD|GROCERY DELIVERY)\b",
        r"\b(PANERA|WENDY'S|KFC|POPEYES|DOMINO'S|DOMINOS|DUNKIN|JIMMY JOHN'S)\b",
        r"\b(GROCERY|SUPERMARKET|MARKETPLACE|FARMERS MARKET)\b",
        r"\b(LIQUOR|WINERY|DISTILLERY|BEER STORE|ALCOHOL)\b",
        r"\b(INSTACART|MEAL KIT|BLUE APRON|HELLOFRESH|DOORDASH|DOOR DASH)\b",
        r"\b(FRESH MARKET|D&W FRESH MARKET|D&W FRESH)\b",
        r"\b(MEIJER|H\.?E\.?B\.?|HEB|SHOPRITE|SHOP RITE|STOP ?& ?SHOP|FOOD LION)\b",
        r"\b(GIANT EAGLE|GIANT\b|HARRIS TEETER|SPROUTS|WINCO|RALPHS|KING SOOPERS)\b",
        r"\b(FRY'S FOOD|FRY'S|FRYS FOOD|JEWEL(?:-?OSCO)?|PIGGLY WIGGLY|MARKET BASKET|ALBERTSONS?)\b",
        r"\b(SPROUTS FARMERS MARKET|BUTCHER SHOP|DELI)\b",
        r"\b(FOOD DELIVERY|MEAL DELIVERY|GROCERY DELIVERY|DELIVERY SERVICE|DRIVE-THRU|DRIVE THRU)\b",
        r"\b(SEAMLESS|GRUBHUB|UBEREATS|POSTMATES|SEAMLESS\.COM)\b",
        r"\b(AMAZONFRESH|WHOLEFOODS MARKET|WHOLEFOODS|GROCERY PICKUP)\b",
        r"\b(PANDA EXPRESS|SUSHI|BISTRO|BAKERY|PASTRY SHOP|CAKE SHOP)\b",
        r"\b(FOOD COURT|FOOD HALL|MEAL PREP|MEAL PLAN|COOKING CLASS)\b",
        r"\b(TIP|TIPS|SERVICE CHARGE|GRATUITY)\b",
        r"\b(FOOD STAMP|EBT PURCHASE|SNACK BAR)\b",
    ],
    "Utilities": [
        r"\b(COMCAST|XFINITY|VERIZON|T-MOBILE|AT&T|ATT\b|ELECTRIC|UTILITY|WATER BILL|GAS BILL|INTERNET)\b",
        r"\b(TRASH|WASTE|SEWER)\b",
        r"\b(DUKE ENERGY|PG&E|PGE|CON EDISON|NATIONAL GRID|SCE|ELECTRIC BILL)\b",
        r"\b(SPECTRUM|CHARTER|COX COMMUNICATIONS|DIRECTV|DISH NETWORK)\b",
        r"\b(NATURAL GAS|GAS SERVICE|WATER SERVICE|UTILITY BILL)\b",
        r"\b(SOLAR LEASE|SOLAR CITY|SUNRUN)\b",
        r"\b(HOSTING|CLOUD STORAGE|GOOGLE WORKSPACE|MICROSOFT 365|AWS|AZURE|DIGITAL OCEAN|SQUARESPACE|WIX|GODADDY|HOSTGATOR)\b",
        r"\b(LEASING OFFICE|RENTAL OFFICE|PROPERTY MANAGEMENT)\b",
        r"\b(WATER DEPARTMENT|WATER BILL|SEWER CHARGE)\b",
        r"\b(HEAT BILL|HEATING OIL|PROPANE|FUEL DELIVERY)\b",
        r"\b(BROADBAND|ISP|CABLE BILL|TELEPHONE|PHONE BILL)\b",
        r"\b(UTILITY SERVICE CHARGE|SERVICE CONNECTION|METER CHARGE)\b",
        r"\b(PHONE SERVICE|CELLULAR SERVICE|MOBILE PLAN|DATA PLAN)\b",
        r"\b(SANITATION|RECYCLING FEE|GARBAGE COLLECTION)\b",
        r"\b(POWER COMPANY|POWER BILL|ELECTRIC COMPANY)\b",
        r"\b(MUNICIPAL UTILITIES|CITY UTILITIES|TOWN UTILITY)\b",
        r"\b(LANDLINE|VOIP|HOME PHONE|TELEPHONE BILL)\b",
        r"\b(INTERNET SERVICE|BROADBAND PROVIDER|DSL|FIBER)\b",
        r"\b(UTILITY DEPOSIT|UTILITY SETUP|SERVICE INSTALLATION)\b",
        r"\b(UTILITY TAX|UTILITY SURCHARGE|SERVICE TAX)\b",
    ],
    "Health": [
        r"\b(PHARMACY|CVS|WALGREENS|RITE AID|DENTAL|DENTIST|ORTHO|HOSPITAL|MEDICAL|HEALTH|CLINIC)\b",
        r"\b(INSURANCE|INS PREM|GEICO|STATE FARM|ALLSTATE|PROGRESSIVE)\b",
        r"\b(DR\.?\s+[A-Z]|DR\.?\b|M\.?D\.?\b|DDS\b|DPM\b|DO\b)",
        r"\b(BLUE CROSS|BLUE SHIELD|AETNA|CIGNA|KAISER|UNITED HEALTH)\b",
        r"\b(OPTUM|LABCORP|QUEST DIAGNOSTICS|RADIOLOGY|IMAGING CENTER|MAMMOGRAPHY|BLOOD DRAW)\b",
        r"\b(PHYSICAL THERAPY|PT VISIT|OCCUPATIONAL THERAPY|SPEECH THERAPY)\b",
        r"\b(URGENT CARE|WALK-IN CLINIC|EMERGENCY ROOM|ER VISIT)\b",
        r"\b(VISION CENTER|OPTICAL|EYE CARE|DERMATOLOGY|PEDIATRIC|CARDIOLOGY|HEALTHCARE SUPPLIES)\b",
        r"\b(MEDICAL BILL|BILLING OFFICE|PHYSICIAN OFFICE|SURGERY CENTER|HOSPITAL BILL)\b",
        r"\b(TELEHEALTH|TELADOC|VIRTUAL VISIT|ONLINE DOCTOR)\b",
        r"\b(AMAZON PHARMACY|GOODRX|PRESCRIPTION|RX REFILL|PHARMACY RX)\b",
        r"\b(CHIROPRACTOR|ACUPUNCTURE|MASSAGE THERAPIST|MASSAGE)\b",
        r"\b(OPTOMETRIST|EYE EXAM|CONTACT LENS|GLASSES|OPHTHALMOLOGY)\b",
        r"\b(MENTAL HEALTH|PSYCHIATRY|PSYCHOLOGY|THERAPY|THERAPIST)\b",
        r"\b(VACCINATION|IMMUNIZATION|VACCINE)\b",
        r"\b(DURABLE MEDICAL|DME|MEDICAL EQUIPMENT|ORTHOTIC)\b",
        r"\b(PHYSICIAN GROUP|MEDICAL GROUP|HEALTH GROUP)\b",
        r"\b(URGENT CARE CENTER|MINOR EMERGENCY|SAME DAY CLINIC)\b",
        r"\b(MEDICATION|PRESCRIPTION CHARGE|RX CHARGE)\b",
        r"\b(HEALTH INSURANCE PREMIUM|MEDICARE|MEDICAID)\b",
    ],
    "Recreation": [
        r"\b(SPOTIFY|NETFLIX|HULU|DISNEY\+|APPLE MUSIC|GAMESTOP|STEAM|AMC|HBO|PEACOCK)\b",
        r"\b(HOTEL|MARRIOTT|HILTON|AIRBNB|DELTA|UNITED AIR|AMERICAN AIR|BOOKING\.COM|TRAVEL)\b",
        r"\b(AMAZON|TARGET|BEST BUY|ETSY|EBAY|POS PURCHASE|THRIFT|GOODWILL|CRAFTSMANSHIP)\b",
        r"\b(SUBSCRIPTION|SUBSCRIPT|RENEWAL|PLAN FEE)\b",
        r"\b(FASTPASS|TOUR|CRUISE|VACATION|TRAVEL AGENCY)\b",
        r"\b(YOUTUBE PREMIUM|PLAYSTATION|PSN|XBOX LIVE|EPIC GAMES|NINTENDO)\b",
        r"\b(SOUTHWEST|JETBLUE|ALASKA AIR|FRONTIER AIR|RYANAIR|EASYJET)\b",
        r"\b(TICKETMASTER|EVENTBRITE|STUBHUB|FANDANGO|LIVE NATION)\b",
        r"\b(GOLF COURSE|SKI PASS|RESORT FEE|MUSEUM|THEME PARK)\b",
        r"\b(GYM MEMBERSHIP|PILATES|YOGA STUDIO|DANCE CLASS|CROSS?FIT|ORANGE THEORY)\b",
        r"\b(ARTS & CRAFTS|HOBBY SHOP|CRAFT STORE|HOBBY LOBBY|MICROSOFT STORE)\b",
        r"\b(CONCERT|LIVE SHOW|PLAY|IMAX|MOVIE THEATER|CINEMA)\b",
        r"\b(ART GALLERY|MUSEUM GIFT SHOP|WORKSHOP|CLASS|LESSON)\b",
        r"\b(AIRBNB EXPERIENCE|TOUR OPERATOR|ADVENTURE SPORTS|OUTDOOR RENTAL)\b",
        r"\b(STREAMING|VIDEO RENTAL|DVD RENTAL|ON DEMAND)\b",
        r"\b(HOBBY STORE|MODEL SHOP|BOARD GAME|ESCAPE ROOM)\b",
        r"\b(MUSIC STORE|RECORD SHOP|VINYL SHOP)\b",
        r"\b(FESTIVAL|FAIR|CARNIVAL|CONCERT SERIES)\b",
        r"\b(SPORTS EVENT|TEAM STORE|ARENA|STADIUM)\b",
        r"\b(OUTDOOR GEAR|SPORTING GOODS|BIKE RENTAL|SKI RENTAL)\b",
    ],
    "Finance": [
        r"\b(PAYROLL|DIRECT DEP|DIR DEP|ACH CREDIT|SALARY|DEPOSIT|INCOME|PAYMENT FROM)\b",  # income
        r"\b(TRANSFER|XFER|ACH DEBIT|ACH WITHDRAWAL|TO SAVINGS|FROM SAVINGS)\b",  # transfers
        r"\b(REFUND|REVERSAL|RETURNED)\b",  # refunds
        r"\b(OVERDRAFT|NSF|SERVICE CHARGE|MAINTENANCE FEE|FEE\b)\b",  # fees
        r"\b(INTEREST|DIVIDEND)\b",  # interest / earnings
        r"\b(LOAN PAYMENT|STUDENT LOAN|AUTO LOAN)\b",  # loan servicing
        r"\b(TUITION|SCHOOL|UNIVERSITY|COLLEGE|CHARITY|DONATION|FOUNDATION)\b",  # misc financial/charitable
        r"\b(VANGUARD|VANGUARD GROUP|FIDELITY|SCHWAB|CHARLES SCHWAB|ROBINHOOD|ETRADE|MERRILL|MERRILL LYNCH)\b",
        r"\b(COINBASE|CRYPTO|BITCOIN|BLOCKFI|CRYPTO EXCHANGE)\b",
        r"\b(ZELLE|VENMO|PAYPAL|PAYPAL INSTX|CASH APP|SQUARE CASH|APPLE CASH)\b",
        r"\b(IRS PAYMENT|TAX PAYMENT|TAX REFUND|STATE TAX|FED TAX)\b",
        r"\b(BILL PAY|AUTO PAY|DIRECT PAY|ELECTRONIC PAYMENT)\b",
        r"\b(ACH PMT|ACH CREDIT|ACH DEPOSIT|WIRE TRANSFER|WIRE\b)\b",
        r"\b(REFUND CHECK|REIMBURSEMENT|CASHBACK|CASH BACK|LOYALTY REWARD|REWARDS CASH)\b",
        r"\b(CHASE|WELLS FARGO|BANK OF AMERICA|CITI|CITIBANK|US BANK|PNC|ALLY|CAPITAL ONE)\b",
        r"\b(AMERICAN EXPRESS|AMEX|DISCOVER|CARD PAYMENT|CREDIT CARD PAYMENT)\b",
        r"\b(CHECK DEPOSIT|CHECK #|CHECK DEPOSIT|CHECK PAYMENT)\b",
        r"\b(AUTOMATIC PAYMENT|AUTOPAY|RECURRING PAYMENT)\b",
        r"\b(DIVIDEND REINVESTMENT|DRIP|REINVESTMENT)\b",
        r"\b(SERVICE FEE|PROCESSING FEE|PAYMENT PROCESSOR)\b",
    ],
}

FINANCE_FALLBACK_RX = re.compile(
    r"\b(ACH|TRANSFER|XFER|FEE|REFUND|INTEREST|DIVIDEND|DEPOSIT|PAYROLL)\b",
    re.IGNORECASE,
)

TRANSFER_RX = re.compile(
    r"\b(TRANSFER|XFER|TO SAVINGS|FROM SAVINGS|INTERNAL TRANSFER)\b",
    re.IGNORECASE,
)

__all__ = [
    "STATEMENT_PERIOD_RX",
    "DATE_START_RX",
    "AMOUNT_TOKEN_RX",
    "YEAR_IN_RANGE_RX",
    "ACCOUNT_HEADER_RX",
    "ACCOUNT_HEADER_INLINE_RX",
    "DATE_RANGE_RX",
    "HEADER_FOOTER_PATTERNS_RX",
    "DATE_PREFIX_RX",
    "BALANCE_SKIP_RX",
    "CREDIT_CARD_DETECT_PATTERNS",
    "CC_TXN_LINE_RX",
    "CC_SECTION_HEADER_RX",
    "DATE_FORMATS",
    "SKIP_DESC",
    "SKIP_CONTAINS",
    "CC_PAYMENT_KEYWORDS",
    "CC_CREDIT_KEYWORDS",
    "CANONICAL_CATEGORIES",
    "DEFAULT_CATEGORY_REGEX",
    "FINANCE_FALLBACK_RX",
    "TRANSFER_RX",
]
